var whosDonating = [
'Robert J. F. From Massachusetts',
'Joseph M. From California',
'michael m. From Massachusetts',
'Kathleen T. From Florida',
'DAVID G. From New York',
'Robert K. From Massachusetts',
'Virginia J. From Massachusetts',
'Roland H. From Maryland',
'Joann  H. From Arkansas',
'Rizalito A. From New York',
'Paul V. From New York',
'william s. From Florida',
'Joseph L. From Massachusetts',
'David C. From Utah',
'Anita W. From Florida',
'Mary A. From Florida',
'Robert R. From California',
'Robert H. From Massachusetts',
'fred w. From South Dakota',
'Mary S. From Florida',
'ellen r. From Florida',
'Jean M S. From Florida',
'Elliot T. From Missouri',
'Bertha H. From Virginia',
'Julian B. From North Carolina',
'philip s. From Florida',
'Joa B. From Rhode Island',
'Danney & Glenda  C. From Texas',
'Francine S. From California',
'Frank O. From New Mexico',
'Leta F. From Oklahoma',
'Daniel T. From Massachusetts',
'Kenneth S. From South Carolina',
'Margaret R. From North Carolina',
'Linda B. From California',
'Bonnie R. From Florida',
'John D. From California',
'Frank P. From California',
'Allan C. From Wisconsin',
'Chris B. From Oklahoma',
'james t. From Texas',
'Donna P. From Massachusetts',
'Frances G. From Florida',
'Louis S. From Virginia',
'Anthony M. From New York',
'Paul B. From Nebraska',
'Brian H. From Louisiana',
'Cheryl K. From Arizona',
'Andrea A. From California',
'Wade  C. From California',
'Michael E. From Illinois',
'Dianna and Jim W. From Massachusetts',
'James R. From Massachusetts',
'Elliot H. From Massachusetts',
'Stephen G. From Massachusetts',
'Margaret F. From Massachusetts',
'Madeleine L. From Colorado',
'Paul S. From Arizona',
'Harold F. From Ohio',
'Dennis C. From Massachusetts',
'Teresa B. From New York',
'Nancy P. From California',
'Mary D. From Florida',
'Michael C. From Ohio',
'Larry B. From Wisconsin',
'William H. From Nevada',
'Samuel F L. From Utah',
'emily j. From Arizona',
'Cheryl G. From California',
'Patricia S. From Massachusetts',
'Leslie Clark G. From Georgia',
'harold m. From Texas',
'Eleanor M. From Florida',
'Edward M. From Hawaii',
'Robert P. From Michigan',
'PHILLIP P. From New York',
'Preston M. From Missouri',
'MARTIN S. From New Jersey',
'Fran N. From Maryland',
'Donald.  A L. From Florida',
'Keeley B. From South Carolina',
'Harry C. From Kansas',
'Martin R. From Florida',
'ronald b. From Ohio',
'Beth S. From Tennessee',
'Gerry G. From Florida',
'William B. From Florida',
'John B. From Illinois',
'John Herbert S. From Massachusetts',
'Gary H. From Georgia',
'Patricia S. From Massachusetts',
'Bertha N. From Florida',
'James Z. From Pennsylvania',
'Harvey  S. From California',
'John N. From New York',
'Charlene S. From Virginia',
'arthur p. From Texas',
'Jeffrey D. From Colorado',
'JAMES F. From Texas',
'Steve G. From Florida',
'Eva L. From Nevada',
'John H. From Washington',
'Joe F. From California',
'Frances B. From Texas',
'Amanda L W. From Texas',
'Gary  K. From South Carolina',
'Michael F. From Virginia',
'Barbara K. From Delaware',
'John T. From Colorado',
'Stuart C. From Massachusetts',
'Robert D. From Texas',
'Bonnie W. From Delaware',
'Anita F. From Texas',
'andrew m. From New York',
'Suzy V. From Florida',
'b G. From California',
'Douglas K. From California',
'Chi Hau C. From Massachusetts',
'David R. From Massachusetts',
'craig k. From Texas',
'Jay R. From Texas',
'Margaret B. From Florida',
'Gerald H. From California',
'james b. From California',
'John N. From Wyoming',
'Susan W. From Georgia',
'Robert V. From California',
'James R S. From Missouri',
'Dale P. From Pennsylvania',
'Theresa K. From Georgia',
'Deyaun  B. From Texas',
'Jaye B. From Oregon',
'David F. From Minnesota',
'Gordon H. From Washington',
'Carmelita T. From California',
'Mary G. From Indiana',
'robert t. From Massachusetts',
'James J. From Missouri',
'Joyce K. From Texas',
'Sandra S. From Pennsylvania',
'Leigh A. From Nebraska',
'GEORGE B. From New York',
'Linda S. From Pennsylvania',
'Paul S. From Pennsylvania',
'John L. From Massachusetts',
'Rob M. From Florida',
'Anne G. From California',
'Gerald P. From North Carolina',
'William W. From Massachusetts',
'Terry D. From Pennsylvania',
'Sarah J. From California',
'Charles F. From Florida',
'Stewart W W. From Massachusetts',
'GORDON M. From Illinois',
'Gail H. From Tennessee',
'Toni E. From California',
'Clinton D. From California',
'Ron & Lois L. From New Hampshire',
'Ronald P. From California',
'Dr Tony M. From Florida',
'Jim O. From Wisconsin',
'JOE B. From Florida',
'Nancy B. From California',
'Richard G. From Colorado',
'Lori G. From California',
'Noreen V. From Massachusetts',
'Michael  D. From New York',
'Kaleb H. From Arizona',
'Tom S. From Iowa',
'Joseph T. From New York',
'Pasquale A. From Virginia',
'Robert  S. From Missouri',
'elyse m. From California',
'Linda K C. From Ohio',
'Hampden W. From Louisiana',
'PAUL C. From Pennsylvania',
'Josephine C. From Massachusetts',
'Jon Ed R. From Texas',
'Peter F. From Massachusetts',
'George R. From Massachusetts',
'Mark B. From Massachusetts',
'Ernest T. From Massachusetts',
'Sally M. From Florida',
'Duane D. From Missouri',
'Phyllis T. From Massachusetts',
'robert w. From South Carolina',
'Roger D. From Massachusetts',
'Peggy T. From California',
'Linda B. From Georgia',
'Sherwin B. From Connecticut',
'nancy s. From California',
'Bruce W. From Massachusetts',
'Douglas  G. From Mississippi',
'James T. From Texas',
'Arthur G. From New Mexico',
'guy  g. From Connecticut',
'Paula S. From Tennessee',
'Charles T. From Tennessee',
'Lawrence K. From Maryland',
'Anthony B. From Florida',
'Sonia F S. From Florida',
'Leo C. From Massachusetts',
'Raymond K. From New York',
'Noel H. From Texas',
'Merv D. From Oklahoma',
'Fred H. From California',
'John F. From South Carolina',
'stephen k. From Tennessee',
'Marcia  A. From California',
'Robert G. From Florida',
'Renee M. From California',
'James J. From Massachusetts',
'Gary H. From Wisconsin',
'Gary B. From Minnesota',
'Douglas P. From Massachusetts',
'Janice H. From Virginia',
'Sayo E. From Nevada',
'Judith R. From Ohio',
'Arthur L. From North Carolina',
'David K. From Wyoming',
'Rebecca P. From California',
'Robert M. From Mississippi',
'Mark G. From Illinois',
'Glenn P. From New Mexico',
'Dan H. From California',
'Robert E. From Florida',
'Ed M. From Texas',
'Mark W. From California',
'Michael C. From Texas',
'Theodore O. From Texas',
'John J & Lucille W D. From Kentucky',
'Penny  P. From Ohio',
'Judy B. From Virginia',
'Frank J. From Massachusetts',
'John S. From Maryland',
'Rene L. From Massachusetts',
'Mary O. From New York',
'Behrle W H. From Kentucky',
'Roi T. From California',
'Martin M. From California',
'George R. From Georgia',
'Gil B. From New Jersey',
'Rebecca G. From Florida',
'barbara m. From Indiana',
'rex t. From Arkansas',
'Renton  R. From California',
'Dominic M. From New Jersey',
'Ken D. From Illinois',
'Conner N R. From North Carolina',
'PAUL T. From California',
'Ed G. From Georgia',
'John S. From Florida',
'Erik S. From Florida',
'Samuel M S. From Hawaii'

];

var randomDonor = whosDonating[Math.floor(Math.random()*whosDonating.length)];

if (randomDonor.length === 0) {
  randomDonor = "David O. from Virginia";
} 
   
function randomize() {
  document.write('<div style="text-indent: 35px; font-size: 22px; margin: 50px 0px;">');
  document.write('<em><strong style="color: #ba081b;">');
  document.write(randomDonor);
  document.write('</em></strong>') 
  document.write('&nbsp; just donated. &nbsp; <strong style="text-decoration: underline">Now it\'s your turn...</strong>')
  document.write('</div>');
}


//function randomize() {
//  if (randomDonor.length === 0) {
//    document.write('');
//  }
//  else {
//    document.write('<div style="text-indent: 35px; font-size: 22px; margin: 30px 0px;">');
//    document.write('<strong style="color: #ba081b;">Whos Donating: &nbsp; </strong><em>');
//    document.write(randomDonor);
//    document.write('</em></div>');
//  }
//}
